name: sunda_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flame: ^1.15.0
  flutter:
    sdk: flutter
  flutter_js: 0.8.1
  flutter_signature_pad: ^3.0.0
  flutter_svg: ^2.0.10+1
  go_router: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_ui: ^1.0.14
  http: ^1.2.1
  image: ^3.0.1
  image_picker: ^1.0.8
  lottie: ^3.1.2
  path_provider: ^2.1.3
  translator: 1.0.0
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
    - assets/ngalagena/
    - assets/angka/
    - assets/swara/
    - assets/Hint/
    - assets/aplikasi/
  # fonts:
  #   - family: SundaFont
  #     fonts:
  #       - asset: assets/SundaneseUnicode-2.0.ttf
