name: sunda_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flame: ^1.15.0
  flutter:
    sdk: flutter
  flutter_js: 0.7.2
  flutter_signature_pad: ^3.0.0
  flutter_tesseract_ocr: ^0.4.24
  go_router: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^3.0.1
  image_picker: ^1.0.8
  translator: 0.1.6
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
    - assets/ngalagena/
    - assets/angka/
    - assets/swara/
  # fonts:
  #   - family: SundaFont
  #     fonts:
  #       - asset: assets/SundaneseUnicode-2.0.ttf
