name: sunda_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flame: ^1.15.0
  flutter:
    sdk: flutter
  flutter_js: 0.7.2
  go_router: ^13.0.1
  translator: 0.1.6
  vector_math: ^2.1.4
  flutter_signature_pad: ^3.0.0
  flutter_tesseract_ocr: ^0.4.24
  image_picker: ^1.0.8
  image: ^3.0.1
  flusseract: ^0.1.3
  # google_mlkit_digital_ink_recognition: ^0.12.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
    - assets/aksara-sunda.jpeg
  # fonts:
  #   - family: SundaFont
  #     fonts:
  #       - asset: assets/SundaneseUnicode-2.0.ttf
